spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      #entity 다 지우고 실행
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

